openapi: 3.0.1
info:
  title: BUY.BOX Zakupy
  description: Wyszukaj książki po nazwie i zobacz gdzie je kupić
  version: "1.0.0"

servers:
  - url: https://buybox-plugin.onrender.com

paths:
  /get-offers:
    post:
      summary: Pobierz oferty dla produktu
      operationId: getOffers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                  description: Nazwa produktu (np. tytuł książki)
                author:
                  type: string
                  description: Autor książki (opcjonalnie)
      responses:
        '200':
          description: Lista ofert z BUY.BOX
          content:
            application/json:
              schema:
                type: object
                properties:
                  ean:
                    type: string
                  offers:
                    type: object
